#!/usr/bin/env bash

set -e

UserName=""
PassWord=""

echo "${UserName} * ${PassWord} *" > \
  $HOME/chap-secrets

docker rm pptp
docker run \
  -d \
  --name=pptp \
  --privileged \
  --net=host \
  -v $HOME/chap-secrets:/etc/ppp/chap-secrets \
  mobtitude/vpn-pptp
