#!/usr/bin/env bash

cwd="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. ${cwd}/config.sh

set -e

. ${cwd}/chap-secrets.sh

docker run \
  -d \
  --name=PPTP \
  --privileged \
  --net=host \
  -v ${cwd}/chap-secrets:/etc/ppp/chap-secrets \
  mobtitude/vpn-pptp
