#!/usr/bin/env bash

cwd="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"

set -e

UserName=""
PassWord=""

echo "${UserName} * ${PassWord} *" > \
  ${cwd}/chap-secrets

docker run \
  -d \
  --name=PPTP \
  --privileged \
  --net=host \
  -v ${cwd}/chap-secrets:/etc/ppp/chap-secrets \
  mobtitude/vpn-pptp
