#!/usr/bin/env bash

cwd="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
DOWNLOADS="${cwd}/Downloads"
LOGS="${DOWNLOADS}/Logs"

set -e

docker run \
  -d \
  --name FileServer \
  -p 8088:80 \
  -v ${DOWNLOADS}/:/usr/share/nginx/html \
  -v ${LOGS}/:/var/log/nginx \
  nginx
